version: '3.5'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/data/postgres/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  service-challange:
    container_name: service-challange
    image: challange:latest
    restart: always
    ports:
      - "8080:8080"