version: '3.5'

services:
  mysql:
    container_name: database
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql/db_data/:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password

  service-challange:
    container_name: service-challange
    image: indigital/challange:latest
    restart: always
    ports:
      - "8080:8080"